stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-app .
    - docker tag my-app:latest sre-exercise/my-app:$CI_COMMIT_SHORT_SHA

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm test

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker push sre-exercise/my-app:$CI_COMMIT_SHORT_SHA
    - kubectl apply -f kubernetes/deployment.yaml
