stages:
  - build
  - test
  - deploy

variables:
  # Customize these variables based on your project and infrastructure
  APP_NAME: my-web-application
  AWS_ACCESS_KEY: YOUR_AWS_ACCESS_KEY
  AWS_SECRET_KEY: YOUR_AWS_SECRET_KEY
  AWS_REGION: us-west-2
  SSH_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    <YOUR_PRIVATE_KEY_HERE>
    -----END RSA PRIVATE KEY-----

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts
  script:
    - scp -r dist/* your-server-user@your-server-ip:/var/www/html/$APP_NAME
